server:
  port: 7171
spring:
  application:
    name: User-Management
  #DB Config
  data:
    mongodb:
      uri: mongodb://localhost:27017/userdb
      database: userdb
  #Kafka Config
  kafka:
    bootstrap-servers: localhost:9092
    #producer configs
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      #value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Configuring kafka topics for different event types
messaging:
  cable:
    eventtypes:
      USER_REGISTRATION_EVENT: user-registration-topic
      FORGOT_PASSWORD_EVENT: forgot-password-topic
      RESET_PASSWORD_EVENT: forgot-password-topic
      OTP_VERIFICATION_EVENT: otp-verification-topic